FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache openssl

RUN npm install -g pnpm

COPY pnpm-lock.yaml package.json ./

RUN pnpm install --frozen-lockfile

COPY . .

WORKDIR /app/apps/web

CMD ["/bin/sh", "/app/apps/web/entrypoint.sh"]