name: "Build Inbox Zero Docker Image"
run-name: "Build Inbox Zero Docker Image"

on:
  push:
    branches: [ "newTrial" ]

env:
  DOCKER_IMAGE_REGISTRY: "ghcr.io"
  DOCKER_USERNAME: "gowthamkishore3799"

jobs:
  set-version:
    if: github.repository == 'gowthamkishore3799/inbox-zero'
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        run: |
          version=$(cat version.txt | tr -d '\r')
          echo "version=$version" >> $GITHUB_OUTPUT

  build-frontend:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    needs:
      - set-version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_IMAGE_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/web
          file: docker/Dockerfile.web
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.DOCKER_USERNAME }}/inbox-zero:latest
            ghcr.io/${{ env.DOCKER_USERNAME }}/inbox-zero:${{ needs.set-version.outputs.version }}