name: "Build Inbox Zero Docker Image"
run-name: "Build Inbox Zero Docker Image"

on:
  push:
    branches: [ "trails" ]

env:
  DOCKER_IMAGE_REGISTRY: "ghcr.io"
  DOCKER_USERNAME: "gowthamkishore3799"

jobs:
  set-version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.set_version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set version
        id: set_version
        shell: bash
        run: |
          echo "version=$(cat version.txt) | tee -a $GITHUB_OUTPUT"

  build-frontend:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    needs:
      - set-version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_IMAGE_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.web
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.DOCKER_USERNAME }}/inbox-zero:latest
            ghcr.io/${{ env.DOCKER_USERNAME }}/inbox-zero:${{ needs.set_version.outputs.version }}